package godot.gdnative

const val GODOT_METHOD_RPC_MODE_DISABLED: Int = 0

const val GODOT_METHOD_RPC_MODE_MASTER: Int = 3

const val GODOT_METHOD_RPC_MODE_MASTERSYNC: Int = 6

const val GODOT_METHOD_RPC_MODE_PUPPET: Int = 4

const val GODOT_METHOD_RPC_MODE_PUPPETSYNC: Int = 7

const val GODOT_METHOD_RPC_MODE_REMOTE: Int = 1

const val GODOT_METHOD_RPC_MODE_REMOTESYNC: Int = 5

const val GODOT_METHOD_RPC_MODE_SYNC: Int = 2

const val GODOT_PROPERTY_USAGE_STORAGE: Int = 1
const val GODOT_PROPERTY_USAGE_EDITOR: Int = 2
const val GODOT_PROPERTY_USAGE_NETWORK: Int = 4
const val GODOT_PROPERTY_USAGE_EDITOR_HELPER: Int = 8
const val GODOT_PROPERTY_USAGE_CHECKABLE: Int = 16 //used for editing global variables
const val GODOT_PROPERTY_USAGE_CHECKED: Int = 32 //used for editing global variables
const val GODOT_PROPERTY_USAGE_INTERNATIONALIZED: Int = 64 //hint for internationalized strings
const val GODOT_PROPERTY_USAGE_GROUP: Int = 128 //used for grouping props in the editor
const val GODOT_PROPERTY_USAGE_CATEGORY: Int = 256
const val GODOT_PROPERTY_USAGE_STORE_IF_NONZERO: Int = 512 //only store if nonzero
const val GODOT_PROPERTY_USAGE_STORE_IF_NONONE: Int = 1024 //only store if false
const val GODOT_PROPERTY_USAGE_NO_INSTANCE_STATE: Int = 2048
const val GODOT_PROPERTY_USAGE_RESTART_IF_CHANGED: Int = 4096
const val GODOT_PROPERTY_USAGE_SCRIPT_VARIABLE: Int = 8192
const val GODOT_PROPERTY_USAGE_STORE_IF_NULL: Int = 16384
const val GODOT_PROPERTY_USAGE_ANIMATE_AS_TRIGGER: Int = 32768
const val GODOT_PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED: Int = 65536

const val GODOT_PROPERTY_USAGE_DEFAULT = GODOT_PROPERTY_USAGE_STORAGE or GODOT_PROPERTY_USAGE_EDITOR or GODOT_PROPERTY_USAGE_NETWORK
const val GODOT_PROPERTY_USAGE_DEFAULT_INTL = GODOT_PROPERTY_USAGE_STORAGE or GODOT_PROPERTY_USAGE_EDITOR or GODOT_PROPERTY_USAGE_NETWORK or GODOT_PROPERTY_USAGE_INTERNATIONALIZED
const val GODOT_PROPERTY_USAGE_NOEDITOR = GODOT_PROPERTY_USAGE_STORAGE or GODOT_PROPERTY_USAGE_NETWORK
