package godot.gdnative

import godot.core.*

enum class GDNATIVE_API_TYPES {
    GDNATIVE_CORE,
    GDNATIVE_EXT_NATIVESCRIPT,
    GDNATIVE_EXT_PLUGINSCRIPT,
    GDNATIVE_EXT_ANDROID,
    GDNATIVE_EXT_ARVR,
    GDNATIVE_EXT_VIDEODECODER,
    GDNATIVE_EXT_NET;

    companion object {
        fun byValue(value: Int) = values()[value]
    }
}

enum class godot_error {
    GODOT_OK,
    GODOT_FAILED,
    GODOT_ERR_UNAVAILABLE,
    GODOT_ERR_UNCONFIGURED,
    GODOT_ERR_UNAUTHORIZED,
    GODOT_ERR_PARAMETER_RANGE_ERROR,
    GODOT_ERR_OUT_OF_MEMORY,
    GODOT_ERR_FILE_NOT_FOUND,
    GODOT_ERR_FILE_BAD_DRIVE,
    GODOT_ERR_FILE_BAD_PATH,
    GODOT_ERR_FILE_NO_PERMISSION,
    GODOT_ERR_FILE_ALREADY_IN_USE,
    GODOT_ERR_FILE_CANT_OPEN,
    GODOT_ERR_FILE_CANT_WRITE,
    GODOT_ERR_FILE_CANT_READ,
    GODOT_ERR_FILE_UNRECOGNIZED,
    GODOT_ERR_FILE_CORRUPT,
    GODOT_ERR_FILE_MISSING_DEPENDENCIES,
    GODOT_ERR_FILE_EOF,
    GODOT_ERR_CANT_OPEN,
    GODOT_ERR_CANT_CREATE,
    GODOT_ERR_QUERY_FAILED,
    GODOT_ERR_ALREADY_IN_USE,
    GODOT_ERR_LOCKED,
    GODOT_ERR_TIMEOUT,
    GODOT_ERR_CANT_CONNECT,
    GODOT_ERR_CANT_RESOLVE,
    GODOT_ERR_CONNECTION_ERROR,
    GODOT_ERR_CANT_ACQUIRE_RESOURCE,
    GODOT_ERR_CANT_FORK,
    GODOT_ERR_INVALID_DATA,
    GODOT_ERR_INVALID_PARAMETER,
    GODOT_ERR_ALREADY_EXISTS,
    GODOT_ERR_DOES_NOT_EXIST,
    GODOT_ERR_DATABASE_CANT_READ,
    GODOT_ERR_DATABASE_CANT_WRITE,
    GODOT_ERR_COMPILATION_FAILED,
    GODOT_ERR_METHOD_NOT_FOUND,
    GODOT_ERR_LINK_FAILED,
    GODOT_ERR_SCRIPT_FAILED,
    GODOT_ERR_CYCLIC_LINK,
    GODOT_ERR_INVALID_DECLARATION,
    GODOT_ERR_DUPLICATE_SYMBOL,
    GODOT_ERR_PARSE_ERROR,
    GODOT_ERR_BUSY,
    GODOT_ERR_SKIP,
    GODOT_ERR_HELP,
    GODOT_ERR_BUG,
    GODOT_ERR_PRINTER_ON_FIRE;

    companion object {
        fun byValue(value: Int) = values()[value]
    }
}

enum class godot_property_hint {
    GODOT_PROPERTY_HINT_NONE,
    GODOT_PROPERTY_HINT_RANGE,
    GODOT_PROPERTY_HINT_EXP_RANGE,
    GODOT_PROPERTY_HINT_ENUM,
    GODOT_PROPERTY_HINT_EXP_EASING,
    GODOT_PROPERTY_HINT_LENGTH,
    GODOT_PROPERTY_HINT_SPRITE_FRAME,
    GODOT_PROPERTY_HINT_KEY_ACCEL,
    GODOT_PROPERTY_HINT_FLAGS,
    GODOT_PROPERTY_HINT_LAYERS_2D_RENDER,
    GODOT_PROPERTY_HINT_LAYERS_2D_PHYSICS,
    GODOT_PROPERTY_HINT_LAYERS_3D_RENDER,
    GODOT_PROPERTY_HINT_LAYERS_3D_PHYSICS,
    GODOT_PROPERTY_HINT_FILE,
    GODOT_PROPERTY_HINT_DIR,
    GODOT_PROPERTY_HINT_GLOBAL_FILE,
    GODOT_PROPERTY_HINT_GLOBAL_DIR,
    GODOT_PROPERTY_HINT_RESOURCE_TYPE,
    GODOT_PROPERTY_HINT_MULTILINE_TEXT,
    GODOT_PROPERTY_HINT_PLACEHOLDER_TEXT,
    GODOT_PROPERTY_HINT_COLOR_NO_ALPHA,
    GODOT_PROPERTY_HINT_IMAGE_COMPRESS_LOSSY,
    GODOT_PROPERTY_HINT_IMAGE_COMPRESS_LOSSLESS,
    GODOT_PROPERTY_HINT_OBJECT_ID,
    GODOT_PROPERTY_HINT_TYPE_STRING,
    GODOT_PROPERTY_HINT_NODE_PATH_TO_EDITED_NODE,
    GODOT_PROPERTY_HINT_METHOD_OF_VARIANT_TYPE,
    GODOT_PROPERTY_HINT_METHOD_OF_BASE_TYPE,
    GODOT_PROPERTY_HINT_METHOD_OF_INSTANCE,
    GODOT_PROPERTY_HINT_METHOD_OF_SCRIPT,
    GODOT_PROPERTY_HINT_PROPERTY_OF_VARIANT_TYPE,
    GODOT_PROPERTY_HINT_PROPERTY_OF_BASE_TYPE,
    GODOT_PROPERTY_HINT_PROPERTY_OF_INSTANCE,
    GODOT_PROPERTY_HINT_PROPERTY_OF_SCRIPT,
    GODOT_PROPERTY_HINT_MAX;

    companion object {
        fun byValue(value: Int) = values()[value]
    }
}

enum class godot_variant_call_error_error {
    GODOT_CALL_ERROR_CALL_OK,
    GODOT_CALL_ERROR_CALL_ERROR_INVALID_METHOD,
    GODOT_CALL_ERROR_CALL_ERROR_INVALID_ARGUMENT,
    GODOT_CALL_ERROR_CALL_ERROR_TOO_MANY_ARGUMENTS,
    GODOT_CALL_ERROR_CALL_ERROR_TOO_FEW_ARGUMENTS,
    GODOT_CALL_ERROR_CALL_ERROR_INSTANCE_IS_NULL;

    companion object {
        fun byValue(value: Int) = values()[value]
    }
}

enum class godot_variant_operator {
    GODOT_VARIANT_OP_EQUAL,
    GODOT_VARIANT_OP_NOT_EQUAL,
    GODOT_VARIANT_OP_LESS,
    GODOT_VARIANT_OP_LESS_EQUAL,
    GODOT_VARIANT_OP_GREATER,
    GODOT_VARIANT_OP_GREATER_EQUAL,
    GODOT_VARIANT_OP_ADD,
    GODOT_VARIANT_OP_SUBTRACT,
    GODOT_VARIANT_OP_MULTIPLY,
    GODOT_VARIANT_OP_DIVIDE,
    GODOT_VARIANT_OP_NEGATE,
    GODOT_VARIANT_OP_POSITIVE,
    GODOT_VARIANT_OP_MODULE,
    GODOT_VARIANT_OP_STRING_CONCAT,
    GODOT_VARIANT_OP_SHIFT_LEFT,
    GODOT_VARIANT_OP_SHIFT_RIGHT,
    GODOT_VARIANT_OP_BIT_AND,
    GODOT_VARIANT_OP_BIT_OR,
    GODOT_VARIANT_OP_BIT_XOR,
    GODOT_VARIANT_OP_BIT_NEGATE,
    GODOT_VARIANT_OP_AND,
    GODOT_VARIANT_OP_OR,
    GODOT_VARIANT_OP_XOR,
    GODOT_VARIANT_OP_NOT,
    GODOT_VARIANT_OP_IN,
    GODOT_VARIANT_OP_MAX;

    companion object {
        fun byValue(value: Int) = values()[value]
    }
}

enum class godot_variant_type {
    GODOT_VARIANT_TYPE_NIL,
    GODOT_VARIANT_TYPE_BOOL,
    GODOT_VARIANT_TYPE_INT,
    GODOT_VARIANT_TYPE_REAL,
    GODOT_VARIANT_TYPE_STRING,
    GODOT_VARIANT_TYPE_VECTOR2,
    GODOT_VARIANT_TYPE_RECT2,
    GODOT_VARIANT_TYPE_VECTOR3,
    GODOT_VARIANT_TYPE_TRANSFORM2D,
    GODOT_VARIANT_TYPE_PLANE,
    GODOT_VARIANT_TYPE_QUAT,
    GODOT_VARIANT_TYPE_AABB,
    GODOT_VARIANT_TYPE_BASIS,
    GODOT_VARIANT_TYPE_TRANSFORM,
    GODOT_VARIANT_TYPE_COLOR,
    GODOT_VARIANT_TYPE_NODE_PATH,
    GODOT_VARIANT_TYPE_RID,
    GODOT_VARIANT_TYPE_OBJECT,
    GODOT_VARIANT_TYPE_DICTIONARY,
    GODOT_VARIANT_TYPE_ARRAY,
    GODOT_VARIANT_TYPE_POOL_BYTE_ARRAY,
    GODOT_VARIANT_TYPE_POOL_INT_ARRAY,
    GODOT_VARIANT_TYPE_POOL_REAL_ARRAY,
    GODOT_VARIANT_TYPE_POOL_STRING_ARRAY,
    GODOT_VARIANT_TYPE_POOL_VECTOR2_ARRAY,
    GODOT_VARIANT_TYPE_POOL_VECTOR3_ARRAY,
    GODOT_VARIANT_TYPE_POOL_COLOR_ARRAY;

    companion object {
        fun byValue(value: Int) = values()[value]
    }
}

enum class godot_vector3_axis {
    GODOT_VECTOR3_AXIS_X,
    GODOT_VECTOR3_AXIS_Y,
    GODOT_VECTOR3_AXIS_Z;

    companion object {
        fun byValue(value: Int) = values()[value]
    }
}

